spring:
  application:
    name: auth
  config:
    import: optional:configserver:http://localhost:8888
jwt:
  secret: ValidJwtSecretWOW789456132321sse54LKJOJLKDLJ9909ds0989fds09fds654987
  validity-ms: 3600000
